version: '2.1'
orbs:
  node: circleci/node@4.7.0
jobs:
  run-tests:
    docker:
      - image: 'cimg/base:stable'
      - image: 'mongo:5.0'
    steps:
      - checkout
      - run:
          name: Sleeping to wait for MongoDB to start
          command: sleep 60
      - run:
          name: Validating the port is open for MongoDB
          command: dockerize -wait tcp://localhost:27017 -timeout 1m
      - run:
          name: Sleeping to wait for MongoDB to finish starting
          command: sleep 60
      - node/install:
          install-yarn: true
      - node/install-packages
      - run:
          command: npm run test
workflows:
  test_json_proxy:
    jobs:
      - run-tests
