version: '2.1'
orbs:
  node: circleci/node@4.7.0
jobs:
  run-tests:
    docker:
      - image: 'cimg/base:stable'
      - image: circleci/mongo:5.0
        command: [mongod]
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run:
          name: Wait for MongoDB
          command: dockerize -wait tcp://localhost:27017 -timeout 2m
      - node/install-packages
      - run:
          command: npm run test
workflows:
  test_json_proxy:
    jobs:
      - run-tests
