orbs:
  node: circleci/node@4.7.0
  wait-for: cobli/wait-for@0.0.2

version: 2.1

jobs:
  test:
    docker:
      - image: circleci/mongo:latest
    executor:
      name: node/default
    steps:
      - checkout
      - run: node/install-packages
      - run: wait-for/mongo
      - run:
          name: Run tests
          command: npm run test

workflows:
  app-tests:
    jobs:
      - test
