version: '2.1'
orbs:
  node: circleci/node@4.7.0
jobs:
  run-tests:
    docker:
      - image: 'cimg/base:stable'
      - image: 'mongo:5.0'
    steps:
      - checkout
      - run:
          name: Validating the port is open for MongoDB
          command: dockerize -wait tcp://localhost:27017 -timeout 1m
      - node/install
      - node/install-packages
      - run:
          command: node server.js
          background: true
      - run:
          command: npm test
workflows:
  test_json_proxy:
    jobs:
      - run-tests
