orbs:
  node: circleci/node@4.7.0

version: 2.1

jobs:
  test:
    docker:
      - image: circleci/mongo:latest
    steps:
      - checkout
      - run:
          name: Waiting for MongoDB to be ready
          command: dockerize -wait tcp://localhost:27017 -timeout 2m
      - run:
          name: Install dependancies
          command: npm install
      - run:
          name: Run tests
          command: npm run test

workflows:
  app-tests:
    jobs:
      - test
